version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: fastapi
    ports:
      - "5435:5432"
    volumes:
      - "C:/Users/Rodrigo Bravo/Desktop/PruebaTecnica/bd/pg:/var/lib/postgresql/data"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fastapi










